// Generated by scripts/sync-release-metadata.mjs. Do not edit.
export const releaseManifest = {
  "platforms": {
    "linux-x86_64": {
      "artifacts": [
        {
          "bytes": 411,
          "name": "LightTable-0.7.0-linux-x86_64-SHA256SUMS",
          "sha256": "6e34b4bf36424433acb8bcdaa9262f0265740c66c595ed43465943d0d5443a55",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.0/LightTable-0.7.0-linux-x86_64-SHA256SUMS"
        },
        {
          "bytes": 1625,
          "name": "LightTable-0.7.0-linux-x86_64-installers.tar.gz",
          "sha256": "4db7faaddde207af43428a93c28e9305c2e0a7d8f4d6ff7ab61afe56b3548ae2",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.0/LightTable-0.7.0-linux-x86_64-installers.tar.gz"
        },
        {
          "bytes": 363720070,
          "name": "LightTable-0.7.0-linux-x86_64.tar.gz",
          "sha256": "17f3eb7e30320faaf425fc2d039ecfb1cf2a11024b674b58174191f0b61be16f",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.0/LightTable-0.7.0-linux-x86_64.tar.gz"
        },
        {
          "bytes": 103,
          "name": "LightTable-0.7.0-linux-x86_64.tar.gz.sha256",
          "sha256": "7419466a314830d366ab50bfa52fd94091c591f5405cd2dccb678bce49a919ef",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.0/LightTable-0.7.0-linux-x86_64.tar.gz.sha256"
        },
        {
          "bytes": 611,
          "name": "linux-x86_64.json",
          "sha256": "3686fb44a0e58fec3148ca54ca4ec144d218917db5df27700e076557949427a0",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.0/linux-x86_64.json"
        }
      ],
      "build_run_id": "34728318611",
      "build_workflow_revision": "3e074314e3558516f335241d79368cc4b4d380e3",
      "channel": "stable",
      "gates": [],
      "minimum_os": "Ubuntu 24.04+; current Arch Linux/Omarchy",
      "published_at": "2026-09-13T01:21:02Z",
      "signing": "ed25519",
      "source_revision": "3e074314e3558516f335241d79368cc4b4d380e3",
      "state": "published",
      "tag": "v0.7.0",
      "update_owner": "app",
      "validation": {
        "receipts": [
          "https://github.com/reville/lighttable-digital-darkroom/actions/runs/34728318611"
        ],
        "status": "passed"
      },
      "version": "0.7.0"
    },
    "macos-arm64": {
      "artifacts": [
        {
          "bytes": 597,
          "name": "LightTable-0.7.0-beta.1-macos-arm64-SHA256SUMS",
          "sha256": "639510a6e80449491d5f52952cd9569026fba2670fa4c2dce794a255d6789a6b",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/macos-v0.7.0-beta.1/LightTable-0.7.0-beta.1-macos-arm64-SHA256SUMS"
        },
        {
          "bytes": 460,
          "name": "LightTable-0.7.0-beta.1-macos-arm64-installers.tar.gz",
          "sha256": "a4da07d2a1cf7459af43b091873a3e327a7960815f6d51e3ddba2e985eb45656",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/macos-v0.7.0-beta.1/LightTable-0.7.0-beta.1-macos-arm64-installers.tar.gz"
        },
        {
          "bytes": 18533,
          "name": "LightTable-0.7.0-beta.1-macos-arm64-macos-native-acceptance.json",
          "sha256": "f5d1c0d7ae3c4f18e9384005e2935db9fbc754c0187db8addf16bb641692b965",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/macos-v0.7.0-beta.1/LightTable-0.7.0-beta.1-macos-arm64-macos-native-acceptance.json"
        },
        {
          "bytes": 20544,
          "name": "LightTable-0.7.0-beta.1-macos-arm64-macos-release-proof.json",
          "sha256": "52561d316e6396e5784d7c252aff73d9025668e9d189ff0c84cb44fe3c5ec549",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/macos-v0.7.0-beta.1/LightTable-0.7.0-beta.1-macos-arm64-macos-release-proof.json"
        },
        {
          "bytes": 350741389,
          "name": "LightTable-0.7.0-beta.1-macos-arm64.dmg",
          "sha256": "03746019228b0be9a34b7af93e30e9f8aca73254befa83526fc8c3f38bfb9f2e",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/macos-v0.7.0-beta.1/LightTable-0.7.0-beta.1-macos-arm64.dmg"
        },
        {
          "bytes": 106,
          "name": "LightTable-0.7.0-beta.1-macos-arm64.dmg.sha256",
          "sha256": "be2286a67bc653ea4c85ec277f6e4409da28126bce06ece731fb91d2fe2eb9bf",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/macos-v0.7.0-beta.1/LightTable-0.7.0-beta.1-macos-arm64.dmg.sha256"
        }
      ],
      "build_run_id": "34728318611",
      "build_workflow_revision": "3e074314e3558516f335241d79368cc4b4d380e3",
      "channel": "beta",
      "gates": [],
      "minimum_os": "macOS 14 Sonoma or later",
      "published_at": "2026-09-13T01:19:26Z",
      "signing": "ad-hoc",
      "source_revision": "3e074314e3558516f335241d79368cc4b4d380e3",
      "state": "published",
      "tag": "macos-v0.7.0-beta.1",
      "update_owner": "manual",
      "validation": {
        "receipts": [
          "https://github.com/reville/lighttable-digital-darkroom/actions/runs/34728318611"
        ],
        "status": "passed"
      },
      "version": "0.7.0-beta.1"
    },
    "windows-x64": {
      "artifacts": [
        {
          "bytes": 778,
          "name": "LightTable-0.7.0-windows-x64-SHA256SUMS",
          "sha256": "a081ef9c940a0c2d39e5186531c42b10fc5ded3e68b10e5dd7626f9d7eba43ce",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.0/LightTable-0.7.0-windows-x64-SHA256SUMS"
        },
        {
          "bytes": 2275,
          "name": "LightTable-0.7.0-windows-x64-installers.tar.gz",
          "sha256": "a82f5ea1a3ad0f236d6d09b2698bf595e8b23b91776af1c293dadbafcf38454c",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.0/LightTable-0.7.0-windows-x64-installers.tar.gz"
        },
        {
          "bytes": 439207352,
          "name": "LightTable-0.7.0-windows-x64-setup.exe",
          "sha256": "db67325485842ddbce78462e821fc130a99255d74b23d67217f9de18cfdb61d1",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.0/LightTable-0.7.0-windows-x64-setup.exe"
        },
        {
          "bytes": 1805,
          "name": "LightTable-0.7.0-windows-x64-store-candidate-receipt.json",
          "sha256": "5126c2fa4ec12ab312b9cee756020976612d42e589b77abfb726bf8d91d2cde8",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.0/LightTable-0.7.0-windows-x64-store-candidate-receipt.json"
        },
        {
          "bytes": 2887,
          "name": "LightTable-0.7.0-windows-x64-windows-signatures.json",
          "sha256": "84fac936d02009d8825c100d6560590863d1961cd6ab61c7188ebb12051e3078",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.0/LightTable-0.7.0-windows-x64-windows-signatures.json"
        },
        {
          "bytes": 126268,
          "name": "LightTable-0.7.0-windows-x64-windows-store-pe-signatures.json",
          "sha256": "323286756656b22dfd90994e6dfca531006991658af0e224e250fe5023c5190f",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.0/LightTable-0.7.0-windows-x64-windows-store-pe-signatures.json"
        },
        {
          "bytes": 292340435,
          "name": "LightTable-0.7.0-windows-x64.zip",
          "sha256": "0eba22c0784fb729647ad08af04debdfed8cf396322ba1faf3fe223fef5882b7",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.0/LightTable-0.7.0-windows-x64.zip"
        },
        {
          "bytes": 855,
          "name": "appcast-windows-x64.xml",
          "sha256": "dda921a9bbadb790c789643ebd32e45f4924f5ef75efaf08b351a23220ef43bb",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.0/appcast-windows-x64.xml"
        }
      ],
      "build_run_id": "34728318611",
      "build_workflow_revision": "3e074314e3558516f335241d79368cc4b4d380e3",
      "channel": "stable",
      "gates": [],
      "minimum_os": "Windows 10/11 x64",
      "native_run_id": "34730014236",
      "published_at": "2026-09-13T01:21:02Z",
      "signing": "authenticode",
      "source_revision": "3e074314e3558516f335241d79368cc4b4d380e3",
      "state": "published",
      "tag": "v0.7.0",
      "update_owner": "app",
      "validation": {
        "receipts": [
          "https://github.com/reville/lighttable-digital-darkroom/actions/runs/34728318611",
          "https://github.com/reville/lighttable-digital-darkroom/actions/runs/34730014236"
        ],
        "status": "passed"
      },
      "version": "0.7.0"
    }
  },
  "repository": "reville/lighttable-digital-darkroom",
  "schema_version": 1,
  "source_revision": "3e074314e3558516f335241d79368cc4b4d380e3",
  "version": "0.7.0"
};
