// Generated by scripts/sync-release-metadata.mjs. Do not edit.
export const releaseManifest = {
  "platforms": {
    "linux-x86_64": {
      "artifacts": [
        {
          "bytes": 411,
          "name": "LightTable-0.7.9-linux-x86_64-SHA256SUMS",
          "sha256": "0022eb56f01cf0c5a5d841fd09f7d459db2afca6e6e09059a3fb965e9141c652",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.9/LightTable-0.7.9-linux-x86_64-SHA256SUMS"
        },
        {
          "bytes": 1627,
          "name": "LightTable-0.7.9-linux-x86_64-installers.tar.gz",
          "sha256": "be46f43a9d60a8f053da5606787b791b51b27fa55f4f8edee9f778ab1da5f1b1",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.9/LightTable-0.7.9-linux-x86_64-installers.tar.gz"
        },
        {
          "bytes": 458457574,
          "name": "LightTable-0.7.9-linux-x86_64.tar.gz",
          "sha256": "b7a859fde7dfcd96cc6ff4aa890d824705c83945e4d98cda73e61f1357b97660",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.9/LightTable-0.7.9-linux-x86_64.tar.gz"
        },
        {
          "bytes": 103,
          "name": "LightTable-0.7.9-linux-x86_64.tar.gz.sha256",
          "sha256": "c6e7c09e9d388dbd0783fcb074e6d9ca80e070210311b97a088b0cf0de073b97",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.9/LightTable-0.7.9-linux-x86_64.tar.gz.sha256"
        },
        {
          "bytes": 611,
          "name": "linux-x86_64.json",
          "sha256": "19c2f5a76ce2e8b67222f9d3c085a4043b8a499e980175e35ab0e475ac6dd4d1",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.9/linux-x86_64.json"
        }
      ],
      "build_run_id": "35283559261",
      "build_workflow_revision": "72154a20b60e6be4f0175f328a3bed6af1390e2a",
      "channel": "stable",
      "gates": [],
      "minimum_os": "Ubuntu 24.04+; current Arch Linux/Omarchy",
      "published_at": "2026-09-18T15:04:33Z",
      "signing": "ed25519",
      "source_revision": "72154a20b60e6be4f0175f328a3bed6af1390e2a",
      "state": "published",
      "tag": "v0.7.9",
      "update_owner": "app",
      "validation": {
        "receipts": [
          "https://github.com/reville/lighttable-digital-darkroom/actions/runs/35283559261"
        ],
        "status": "passed"
      },
      "version": "0.7.9"
    },
    "macos-arm64": {
      "artifacts": [
        {
          "bytes": 367386775,
          "name": "LightTable-0.7.6-macos-arm64.zip",
          "sha256": "58de0f87bab3371a353a9f2bf46e5ffaf74af05955208726b898b437b63b69c7",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.6/LightTable-0.7.6-macos-arm64.zip"
        },
        {
          "bytes": 99,
          "name": "LightTable-0.7.6-macos-arm64.zip.sha256",
          "sha256": "79b772b224193e6cb38d725117c33e3b622e94be4a1991a57035e19e17162b07",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.6/LightTable-0.7.6-macos-arm64.zip.sha256"
        },
        {
          "bytes": 381009941,
          "name": "LightTable-0.7.6-macos-arm64-notarized.dmg",
          "sha256": "f78353b0799a738bf0da1cabaa62f6d9090fa32c3f3a04459e205daeacf1a496",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.6/LightTable-0.7.6-macos-arm64-notarized.dmg"
        },
        {
          "bytes": 109,
          "name": "LightTable-0.7.6-macos-arm64-notarized.dmg.sha256",
          "sha256": "c6d23f81361857579e88e5751287028364eb4a6012b303d4c3730fd74bda60c1",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.6/LightTable-0.7.6-macos-arm64-notarized.dmg.sha256"
        },
        {
          "bytes": 1586,
          "name": "appcast-macos-arm64.xml",
          "sha256": "30fb778672c57b2e3b774da308dfb502daa804bb75276cab77879b3300f5c673",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.6/appcast-macos-arm64.xml"
        },
        {
          "bytes": 4135,
          "name": "LightTable-0.7.6-macos-arm64-macos-release-proof.json",
          "sha256": "f89cf0acced2689f6251c9b567592ae0e6396858cadd53da289bdb26d6836f41",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.6/LightTable-0.7.6-macos-arm64-macos-release-proof.json"
        }
      ],
      "build_run_id": "34773993435",
      "build_workflow_revision": "d1ef234ec2a67d5bdcdcb94cda5a0bbf07738c13",
      "channel": "stable",
      "gates": [],
      "minimum_os": "macOS 14 Sonoma or later",
      "published_at": "2026-09-15T16:31:55.577983Z",
      "signing": "developer-id-notarized",
      "source_revision": "b89a5c9c594111a65286ab761857f1fb372fe829",
      "state": "published",
      "tag": "v0.7.6",
      "update_owner": "app",
      "validation": {
        "receipts": [
          "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.6/LightTable-0.7.6-macos-arm64-macos-release-proof.json"
        ],
        "status": "passed"
      },
      "version": "0.7.6"
    },
    "windows-x64": {
      "artifacts": [
        {
          "bytes": 778,
          "name": "LightTable-0.7.9-windows-x64-SHA256SUMS",
          "sha256": "4e9bdc3ca4f270a9fb7d159fcf29eaa44ce56671ad917c52b5a3187d2aa47c76",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.9/LightTable-0.7.9-windows-x64-SHA256SUMS"
        },
        {
          "bytes": 2275,
          "name": "LightTable-0.7.9-windows-x64-installers.tar.gz",
          "sha256": "cd68bcfefb84f94cfda8773640a63b984631cfdc61e2817b43af8b2b1e5f7f0d",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.9/LightTable-0.7.9-windows-x64-installers.tar.gz"
        },
        {
          "bytes": 524413552,
          "name": "LightTable-0.7.9-windows-x64-setup.exe",
          "sha256": "cc644b34dd6a3992fa71887923e8b8a733f6232165980676b4318bb4669f6b6d",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.9/LightTable-0.7.9-windows-x64-setup.exe"
        },
        {
          "bytes": 1805,
          "name": "LightTable-0.7.9-windows-x64-store-candidate-receipt.json",
          "sha256": "990d5dcfa8a2512bb1000e996b16d18e19a54cca68fe12d0dcbf5ad97142b0d1",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.9/LightTable-0.7.9-windows-x64-store-candidate-receipt.json"
        },
        {
          "bytes": 2887,
          "name": "LightTable-0.7.9-windows-x64-windows-signatures.json",
          "sha256": "4f51bb374ba16530fabc710c7f320fa1caa049579b58f9927c4017819de41cd3",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.9/LightTable-0.7.9-windows-x64-windows-signatures.json"
        },
        {
          "bytes": 135532,
          "name": "LightTable-0.7.9-windows-x64-windows-store-pe-signatures.json",
          "sha256": "22952220f96c1431b031f860568436cd9c2ed73638126692b86441cf864f65d1",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.9/LightTable-0.7.9-windows-x64-windows-store-pe-signatures.json"
        },
        {
          "bytes": 394385607,
          "name": "LightTable-0.7.9-windows-x64.zip",
          "sha256": "0ce97c2c6c91bb9c45c13867b6c0ce598c5b30501156cdfe024822d94775eed1",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.9/LightTable-0.7.9-windows-x64.zip"
        },
        {
          "bytes": 855,
          "name": "appcast-windows-x64.xml",
          "sha256": "ba61af99c63a001b93474cb1240ace4d2d307e46b92cb1a0384289d13bab7243",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.9/appcast-windows-x64.xml"
        }
      ],
      "build_run_id": "35283559261",
      "build_workflow_revision": "72154a20b60e6be4f0175f328a3bed6af1390e2a",
      "channel": "stable",
      "gates": [],
      "minimum_os": "Windows 10/11 x64",
      "native_run_id": "35351530996",
      "published_at": "2026-09-18T15:04:33Z",
      "signing": "authenticode",
      "source_revision": "72154a20b60e6be4f0175f328a3bed6af1390e2a",
      "state": "published",
      "tag": "v0.7.9",
      "update_owner": "app",
      "validation": {
        "receipts": [
          "https://github.com/reville/lighttable-digital-darkroom/actions/runs/35283559261",
          "https://github.com/reville/lighttable-digital-darkroom/actions/runs/35351530996"
        ],
        "status": "passed"
      },
      "version": "0.7.9"
    }
  },
  "repository": "reville/lighttable-digital-darkroom",
  "schema_version": 1,
  "source_revision": "72154a20b60e6be4f0175f328a3bed6af1390e2a",
  "version": "0.7.9"
};
