// Generated by scripts/sync-release-metadata.mjs. Do not edit.
export const releaseManifest = {
  "platforms": {
    "linux-x86_64": {
      "artifacts": [
        {
          "bytes": 414,
          "name": "LightTable-0.7.10-linux-x86_64-SHA256SUMS",
          "sha256": "70dde701a242cde92d8b20dd5e6706b365159dd38a11701d0985ff1ee5d0d51a",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.10/LightTable-0.7.10-linux-x86_64-SHA256SUMS"
        },
        {
          "bytes": 1625,
          "name": "LightTable-0.7.10-linux-x86_64-installers.tar.gz",
          "sha256": "c5c15ca75d26bf76d3902ba6d6d9d8c63a84a83acfaf634af2a43da09155f5ba",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.10/LightTable-0.7.10-linux-x86_64-installers.tar.gz"
        },
        {
          "bytes": 458466104,
          "name": "LightTable-0.7.10-linux-x86_64.tar.gz",
          "sha256": "f5913d47653aedde4e64e7eb0494e1ec45749f7c1dcf3581b3b8b8241563765b",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.10/LightTable-0.7.10-linux-x86_64.tar.gz"
        },
        {
          "bytes": 104,
          "name": "LightTable-0.7.10-linux-x86_64.tar.gz.sha256",
          "sha256": "073d2e1a7a24fa886e4a018ac7dbc0d42a26b31587cf051d7fea4f9baeb39b1c",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.10/LightTable-0.7.10-linux-x86_64.tar.gz.sha256"
        },
        {
          "bytes": 615,
          "name": "linux-x86_64.json",
          "sha256": "a2adc5b571ed426dfe4b3e4c0fe7364f76d73bc4789f29e19741b313b9bb9365",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.10/linux-x86_64.json"
        }
      ],
      "build_run_id": "35390515279",
      "build_workflow_revision": "75a719e0b4bec18371ea62f879440316dbab7560",
      "channel": "stable",
      "gates": [],
      "minimum_os": "Ubuntu 24.04+; current Arch Linux/Omarchy",
      "published_at": "2026-09-18T21:14:01Z",
      "signing": "ed25519",
      "source_revision": "75a719e0b4bec18371ea62f879440316dbab7560",
      "state": "published",
      "tag": "v0.7.10",
      "update_owner": "app",
      "validation": {
        "receipts": [
          "https://github.com/reville/lighttable-digital-darkroom/actions/runs/35390515279"
        ],
        "status": "passed"
      },
      "version": "0.7.10"
    },
    "macos-arm64": {
      "artifacts": [
        {
          "bytes": 367386775,
          "name": "LightTable-0.7.6-macos-arm64.zip",
          "sha256": "58de0f87bab3371a353a9f2bf46e5ffaf74af05955208726b898b437b63b69c7",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.6/LightTable-0.7.6-macos-arm64.zip"
        },
        {
          "bytes": 99,
          "name": "LightTable-0.7.6-macos-arm64.zip.sha256",
          "sha256": "79b772b224193e6cb38d725117c33e3b622e94be4a1991a57035e19e17162b07",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.6/LightTable-0.7.6-macos-arm64.zip.sha256"
        },
        {
          "bytes": 381009941,
          "name": "LightTable-0.7.6-macos-arm64-notarized.dmg",
          "sha256": "f78353b0799a738bf0da1cabaa62f6d9090fa32c3f3a04459e205daeacf1a496",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.6/LightTable-0.7.6-macos-arm64-notarized.dmg"
        },
        {
          "bytes": 109,
          "name": "LightTable-0.7.6-macos-arm64-notarized.dmg.sha256",
          "sha256": "c6d23f81361857579e88e5751287028364eb4a6012b303d4c3730fd74bda60c1",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.6/LightTable-0.7.6-macos-arm64-notarized.dmg.sha256"
        },
        {
          "bytes": 1586,
          "name": "appcast-macos-arm64.xml",
          "sha256": "30fb778672c57b2e3b774da308dfb502daa804bb75276cab77879b3300f5c673",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.6/appcast-macos-arm64.xml"
        },
        {
          "bytes": 4135,
          "name": "LightTable-0.7.6-macos-arm64-macos-release-proof.json",
          "sha256": "f89cf0acced2689f6251c9b567592ae0e6396858cadd53da289bdb26d6836f41",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.6/LightTable-0.7.6-macos-arm64-macos-release-proof.json"
        }
      ],
      "build_run_id": "34773993435",
      "build_workflow_revision": "d1ef234ec2a67d5bdcdcb94cda5a0bbf07738c13",
      "channel": "stable",
      "gates": [],
      "minimum_os": "macOS 14 Sonoma or later",
      "published_at": "2026-09-15T16:31:55.577983Z",
      "signing": "developer-id-notarized",
      "source_revision": "b89a5c9c594111a65286ab761857f1fb372fe829",
      "state": "published",
      "tag": "v0.7.6",
      "update_owner": "app",
      "validation": {
        "receipts": [
          "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.6/LightTable-0.7.6-macos-arm64-macos-release-proof.json"
        ],
        "status": "passed"
      },
      "version": "0.7.6"
    },
    "windows-x64": {
      "artifacts": [
        {
          "bytes": 784,
          "name": "LightTable-0.7.10-windows-x64-SHA256SUMS",
          "sha256": "2224fe1fe5577e0687891ff9a5faccc3d26615a846bbbc37fa7009c1bcd6ca98",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.10/LightTable-0.7.10-windows-x64-SHA256SUMS"
        },
        {
          "bytes": 2283,
          "name": "LightTable-0.7.10-windows-x64-installers.tar.gz",
          "sha256": "1ef7b4352e3cb6f46c242cd46fe44326d678a691a13479b18ea438e6f67ad784",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.10/LightTable-0.7.10-windows-x64-installers.tar.gz"
        },
        {
          "bytes": 524440176,
          "name": "LightTable-0.7.10-windows-x64-setup.exe",
          "sha256": "b42634fb567c2c4acaeae69d66d708d8eea0965d73417d2228d3e4be5c10f2b1",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.10/LightTable-0.7.10-windows-x64-setup.exe"
        },
        {
          "bytes": 1808,
          "name": "LightTable-0.7.10-windows-x64-store-candidate-receipt.json",
          "sha256": "b43577ee242fbc054f2ed7fa569ab6de356e146436d47367a75bfbb050a84cb8",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.10/LightTable-0.7.10-windows-x64-store-candidate-receipt.json"
        },
        {
          "bytes": 2889,
          "name": "LightTable-0.7.10-windows-x64-windows-signatures.json",
          "sha256": "615bc2591cd08b0f084775182a49b0a703cc6475490c36e56dd03559cb75bea8",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.10/LightTable-0.7.10-windows-x64-windows-signatures.json"
        },
        {
          "bytes": 135532,
          "name": "LightTable-0.7.10-windows-x64-windows-store-pe-signatures.json",
          "sha256": "b4543993696deb43250cad4fc6e5b45eb87a7072ab2f3955b24ab6ea5bcb2b55",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.10/LightTable-0.7.10-windows-x64-windows-store-pe-signatures.json"
        },
        {
          "bytes": 394397046,
          "name": "LightTable-0.7.10-windows-x64.zip",
          "sha256": "c53efd346b6daaa5b660458a6364e49b650139b30002a5788af6942022f67567",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.10/LightTable-0.7.10-windows-x64.zip"
        },
        {
          "bytes": 861,
          "name": "appcast-windows-x64.xml",
          "sha256": "bfc047ba164b0fea5b9975f1cf0d613de65705ffafa92a5bee91d20ba808a4f7",
          "url": "https://github.com/reville/lighttable-digital-darkroom/releases/download/v0.7.10/appcast-windows-x64.xml"
        }
      ],
      "build_run_id": "35390515279",
      "build_workflow_revision": "75a719e0b4bec18371ea62f879440316dbab7560",
      "channel": "stable",
      "gates": [],
      "minimum_os": "Windows 10/11 x64",
      "native_run_id": "35395072859",
      "published_at": "2026-09-18T21:14:01Z",
      "signing": "authenticode",
      "source_revision": "75a719e0b4bec18371ea62f879440316dbab7560",
      "state": "published",
      "tag": "v0.7.10",
      "update_owner": "app",
      "validation": {
        "receipts": [
          "https://github.com/reville/lighttable-digital-darkroom/actions/runs/35390515279",
          "https://github.com/reville/lighttable-digital-darkroom/actions/runs/35395072859"
        ],
        "status": "passed"
      },
      "version": "0.7.10"
    }
  },
  "repository": "reville/lighttable-digital-darkroom",
  "schema_version": 1,
  "source_revision": "75a719e0b4bec18371ea62f879440316dbab7560",
  "version": "0.7.10"
};
